import React from 'react';
import PropTypes from 'prop-types';
import { StyleSheet, View, StatusBar, ScrollView } from 'react-native';
import ButtonWithImage from '../Button/ButtonWithImage';
import ButtonSelector from '../MenuBar/ButtonSelector';
import GestureRecognizer from 'react-native-swipe-gestures';
import Modal from 'react-native-modal';
import testData from '../Resources/CardTestData';
import Moment from 'moment';

import Home from '../screens/HomePage';
import Calendar from '../screens/Calendar';
import MedicineView from '../screens/MedicineView';
import Settings from '../screens/Settings';
import FlatListCard from '../screens/FlatListCard';

const MEDICINE_PAGE = 'medicine';
const SETTINGS_PAGE = 'settings';
const HOME_PAGE = 'home';
const CALENDAR_PAGE = 'calendar';
const SYMPTOMS_LIST = 'flatlistcard';

const SELECTED_BACKGROUND_COLOR = '#cc99ff';
const DEFAULT_BACKGROUND_COLOR = '#ffffff';
const QUICK_LOG_COLOR = '#cc99ff';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end'
  },
  inputButtonContainer: {
    height: 200
  },
  addButton: {
    height: 75,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#ffffff',
    alignItems: 'flex-end'
  },
  menuButtons: {
    height: 150,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#ffffff'
  },
  bottomModal: {
    justifyContent: 'flex-end'
  },
  menuStyle: {
    justifyContent: 'space-around',
    height: 100,
    flexDirection: 'row'
  }
});

class MenuBar extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      buttonsVisible: false,
      menuVisible: false,
      data: testData,
      selectedID: HOME_PAGE
    };
    idCounter = testData.length + 1;
  }
  _addNewItem(name, t) {
    var dt = Date.now();
    idCounter += 1;
    if (name == 'random-user') {
      fetch('https://randomuser.me/api/?inc=gender,name,nat&nat=us')
        .then(response => response.json())
        .then(data => {
          testData.splice(0, 0, {
            id: idCounter,
            image: require('../Resources/profilePic.jpg'),
            title: data.results[0].name.first + ' ' + data.results[0].name.last,
            timeStamp: Moment(dt).format('h:mm:ss'),
            note1: data.results[0].gender,
            note2: data.results[0].nat,
            swiperActive: true
          });
        });
    } else if (name == 'Medicine') {
      testData.splice(0, 0, {
        id: idCounter,
        title: 'Medicine',
        image: require('../Resources/medicine.png'),
        timeStamp: Moment(dt).format('h:mm:ss'),
        note1: 'Autogenerated',
        note2: '3 Pills a day',
        swiperActive: true
      });
    } else if (name == 'Weight') {
      testData.splice(0, 0, {
        id: idCounter,
        title: 'Weight Change',
        image: require('../Resources/scale.png'),
        timeStamp: Moment(dt).format('h:mm:ss'),
        note1: 'Autogenerated',
        note2: 'You gained weight',
        swiperActive: true
      });
    } else if (name == 'Pain') {
      testData.splice(0, 0, {
        id: idCounter,
        title: 'Pain!',
        image: require('../Resources/intensePain.png'),
        timeStamp: Moment(dt).format('h:mm:ss'),
        note1: 'Autogenerated',
        note2: 'You are in pain!',
        swiperActive: true
      });
    } else {
      testData.splice(0, 0, {
        id: idCounter,
        iconName: name,
        title: t,
        timeStamp: Moment(dt).format('h:mm:ss'),
        note1: 'Autogenerated',
        note2: 'Duration: xx min',
        swiperActive: true
      });
    }
    this.setState({
      data: testData,
      buttonsVisible: false,
      menuVisible: false,
      selectedID: SYMPTOMS_LIST
    });
  }
  _renderScreen() {
    switch (this.state.selectedID) {
      case HOME_PAGE:
        return <Home />;
        break;
      case CALENDAR_PAGE:
        return <Calendar />;
        break;
      case MEDICINE_PAGE:
        return <MedicineView />;
        break;
      case SETTINGS_PAGE:
        return <Settings />;
        break;
      case SYMPTOMS_LIST:
        return <FlatListCard data={this.state.data} extraData={this.state} />;
        break;
    }
  }

  render() {
    let page = this._renderScreen();

    return (
      <View style={styles.container}>
        {page}
        <View style={styles.addButton}>
          <Modal
            onSwipe={() => this.setState({ menuVisible: false })}
            swipeDirection="down"
            onBackdropPress={() => this.setState({ menuVisible: false })}
            style={styles.bottomModal}
            isVisible={this.state.menuVisible}
          >
            <View style={styles.menuStyle}>
              <ButtonWithImage
                imageSource={require('../Resources/medicine.png')}
                backgroundColor={QUICK_LOG_COLOR}
                onPress={() => this._addNewItem('Medicine', 'Medicine')}
                height={75}
                width={75}
                rounded={true}
              />
              <ButtonWithImage
                imageSource={require('../Resources/intensePain.png')}
                backgroundColor={QUICK_LOG_COLOR}
                onPress={() => this._addNewItem('Pain', 'Pain')}
                height={75}
                width={75}
                rounded={true}
              />
            </View>
          </Modal>
          <Modal
            onBackdropPress={() => this.setState({ buttonsVisible: false })}
            style={styles.bottomModal}
            isVisible={this.state.buttonsVisible}
          >
            <View style={{ height: 150 }}>
              <ScrollView style={styles.inputButtonContainer} horizontal={true}>
                <ButtonWithImage
                  text={'Headache'}
                  onPress={() => this._addNewItem('headache', 'Headache')}
                  imageSource={require('../Resources/headPain.png')}
                  backgroundColor={'#7c0920'}
                  color={'#ffffff'}
                  rounded={true}
                />
                <ButtonWithImage
                  text={'Neck Pain'}
                  onPress={() => this._addNewItem('neck-pain', 'Neck Pain')}
                  imageSource={require('../Resources/neckPain.png')}
                  backgroundColor={'#b43649'}
                  color={'#ffffff'}
                  rounded={true}
                />
                <ButtonWithImage
                  text={'Leg Pain'}
                  onPress={
                    (onPress = () => {
                      this._addNewItem('leg-pain', 'Leg Pain');
                    })
                  }
                  imageSource={require('../Resources/legPain.png')}
                  backgroundColor={'#7c0920'}
                  color={'white'}
                  rounded={true}
                />
                <ButtonWithImage
                  text={'Random User'}
                  onPress={() => this._addNewItem('random-user', '')}
                  imageSource={require('../Resources/profilePic.png')}
                  backgroundColor={'#b43649'}
                  color={'#ffffff'}
                  rounded={true}
                />
              </ScrollView>
            </View>
          </Modal>
          <ButtonSelector
            imageSource={require('../Resources/homeIcon.png')}
            width={50}
            height={50}
            rounded={true}
            defaultBackgroundColor={DEFAULT_BACKGROUND_COLOR}
            selectedBackgroundColor={SELECTED_BACKGROUND_COLOR}
            selected={this.state.selectedID == HOME_PAGE}
            onPress={() => {
              this.setState({
                selectedID: HOME_PAGE
              });
            }}
          />

          <ButtonSelector
            imageSource={require('../Resources/calendar.png')}
            width={50}
            height={50}
            rounded={true}
            defaultBackgroundColor={DEFAULT_BACKGROUND_COLOR}
            selectedBackgroundColor={SELECTED_BACKGROUND_COLOR}
            selected={this.state.selectedID == CALENDAR_PAGE}
            onPress={() => {
              this.setState({
                selectedID: CALENDAR_PAGE
              });
            }}
          />
          <GestureRecognizer
            onSwipeUp={() => this.setState({ buttonsVisible: true })}
          >
            <ButtonWithImage
              shadow={true}
              rounded={true}
              imageSource={require('../Resources/plusSign2.png')}
              width={50}
              height={50}
              onPress={() => {
                this.setState({
                  menuVisible: true
                });
              }}
              onLongPress={() => {
                this.setState({
                  buttonsVisible: true
                });
              }}
            />
          </GestureRecognizer>
          <ButtonSelector
            imageSource={require('../Resources/pillBottle.png')}
            width={50}
            height={50}
            rounded={true}
            defaultBackgroundColor={DEFAULT_BACKGROUND_COLOR}
            selectedBackgroundColor={SELECTED_BACKGROUND_COLOR}
            selected={this.state.selectedID == MEDICINE_PAGE}
            onPress={() => {
              this.setState({
                selectedID: MEDICINE_PAGE
              });
            }}
          />
          <ButtonSelector
            imageSource={require('../Resources/settings.png')}
            width={50}
            height={50}
            rounded={true}
            defaultBackgroundColor={DEFAULT_BACKGROUND_COLOR}
            selectedBackgroundColor={SELECTED_BACKGROUND_COLOR}
            selected={this.state.selectedID == SETTINGS_PAGE}
            onPress={() => {
              this.setState({
                selectedID: SETTINGS_PAGE
              });
            }}
          />
        </View>
      </View>
    );
  }
}
export default MenuBar;
